apiVersion: v1
kind: ServiceAccount
metadata:
  name: ix-feature-discovery
  namespace: node-feature-discovery
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ix-feature-discovery
  namespace: node-feature-discovery
rules:
  - apiGroups:
      - nfd.k8s-sigs.io
    resources:
      - nodefeatures
    verbs:
      - get
      - list
      - watch
      - create
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ix-feature-discovery
  namespace: node-feature-discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ix-feature-discovery
subjects:
  - kind: ServiceAccount
    name: ix-feature-discovery
    namespace: node-feature-discovery
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ix-feature-discovery
  namespace: node-feature-discovery
  labels:
    app.kubernetes.io/name: ix-feature-discovery
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ix-feature-discovery
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ix-feature-discovery
    spec:
      serviceAccountName: ix-feature-discovery
      containers:
        - image: "iluvatarcorex/ix-feature-discovery:v0.1.0"
          imagePullPolicy: IfNotPresent
          name: ix-feature-discovery
          command: ["/usr/bin/ix-feature-discovery"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: output-dir
              mountPath: "/etc/kubernetes/node-feature-discovery/features.d"
            - name: host-sys
              mountPath: "/sys"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: output-dir
          hostPath:
            path: "/etc/kubernetes/node-feature-discovery/features.d"
        - name: host-sys
          hostPath:
            path: "/sys"
